name: EIM
favicon: null
layout_spectrum: 0.4981682011857629
typography_spectrum: 0.9763593156822026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6542853303253651
  lightness: 0.9722946586553007
  saturation: 0.25184995285235345
  rhythmicContrast: 0.5905484601389617
purpose: []
