favicon: null
name: EIM
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.0625
  brandStrength: 0.8432836
  lightness: 0.7378731
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#D95604'
    - '#F4BE26'
    - '#E669A1'
  rhythmicContrast: 0.6595149
typography_spectrum: 0.4868421
layout_spectrum: 0.6572682
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
